platform :ios, '9.0'

target 'TestApp' do

  use_frameworks!
	pod 'AlamofireDomain', '~> 4.1’
	pod 'Kingfisher', '~> 3.2’
	pod 'AlamofireObjectMapper' 
	pod 'AlamofireSwiftyJSON’
	pod 'MBProgressHUD'

  target 'TestAppTests' do
    inherit! :search_paths
  end

  target 'TestAppUITests' do
    inherit! :search_paths
  end

end
